# Site settings
title: First Berlin Toastmasters - "We support, you succeed"
email: 
description: > # this means to ignore newlines until "baseurl:"
  First Berlin Toastmasters is a non-profit organisation dedicated to teaching leadership and public speaking skills.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.fbtm.org" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
gems: ['zurb-foundation']

meeting_address: |
  Umweltbundesamt (Room 1042)
  Bismarckplatz 1
  14193 Berlin-Wilmersdorf

default_image:
  feature: banners/members-1900x350.jpg
  credit: First Berlin Toastmasters
  creditlink: http://fbtm.org/
