# Site settings
title: First Berlin Toastmasters - "We support, you succeed"
email: 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.fbtm.org" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
gems: ['zurb-foundation']

meeting_address: >
  Umweltbundesamt (Room 1042)
  Bismarckplatz 1
  14193 Berlin-Wilmersdorf

default_image:
  feature: banners/public-speaking-banner.jpg
  credit: Pete
  creditlink: https://www.flickr.com/photos/comedynose/3638971241/
